apiVersion: v1
kind: Service
metadata:
  name: mcp-chat
  labels:
    {{- include "mcp-chat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mcp-chat.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
