apiVersion: v1
kind: Service
metadata:
  name: mcp-index
  labels:
    {{- include "mcp-index.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mcp-index.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
